// Generated by https://pagedraw.io/pages/8599
import React from 'react';
import './chargify.css';
import Table from '../components/table.js';

const JsonTable = require('ts-react-json-table');

function render() {
    return <div className="chargify-chargify-1">
        <div className="chargify-0">
            <div className="chargify-0-0" /> 
            <div className="chargify-container-5">
                <Table />
            </div>
            <div className="chargify-0-2" /> 
        </div>
        <div className="chargify-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}