// Generated by https://pagedraw.io/pages/8599


import Pdtable from './pdtable';
import React from 'react';
import './chargify.css';

function render() {
    return <div className="chargify-chargify-1">
        <div className="chargify-0">
            <div className="chargify-text-3">Here is some text</div>
        </div>
        <div className="chargify-1">
            <div className="chargify-1-0" /> 
            <div className="chargify-rectangle_2">
                <div className="chargify-1-1-0">
                    <div className="chargify-1-1-0-0">
                        <div className="chargify-1-1-0-0-0">
                            <div className="chargify-rectangle-1">
                                <div className="chargify-1-1-0-0-0-0-0">
                                    <div className="chargify-table-3"><Pdtable /> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="chargify-1-1-0-1">
                        <div className="chargify-1-1-0-1-0">
                            <div className="chargify-oval-1" /> 
                        </div>
                    </div>
                </div>
            </div>
            <div className="chargify-1-2" /> 
        </div>
        <div className="chargify-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}