// Generated by https://pagedraw.io/pages/8599
import Table from '../components/table.js';
import React from 'react';
import './pdtable.css';

function render() {
    return <div className="pdtable-pdtable-8"><Table /></div>;
};

export default function(props) {
    return render.apply({props: props});
}